version: "3.9"

networks:
  app_network:
    driver: bridge

services:
  inventory-database:
    image: postgres:16.3-alpine
    networks:
      - app_network
    container_name: inventory-database
    ports:
      - ${INVENTORY_POSTGRES_HOST_PORT}:${INVENTORY_POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${INVENTORY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${INVENTORY_POSTGRES_PASSWORD}
      - POSTGRES_DB=${MOVIES_DB}
    volumes:
      - ./srcs/inventory-app/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - inventory_postgres_data:/var/lib/postgresql/data

  billing-database:
    image: postgres:16.3-alpine
    networks:
      - app_network
    container_name: billing-database
    ports:
      - ${BILLING_POSTGRES_HOST_PORT}:${BILLING_POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${BILLING_POSTGRES_USER}
      - POSTGRES_PASSWORD=${BILLING_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDERS_DB}
    volumes:
      - ./srcs/billing-app/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - billing_postgres_data:/var/lib/postgresql/data
  
  rabbitmq:
    image: rabbitmq:3-management
    networks:
      - app_network
    container_name: RabbitMQ
    ports:
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
      - 15672:15672

  inventory-app:
    build:
      context: ./srcs/inventory-app
      dockerfile: Dockerfile
    networks:
      - app_network
    container_name: inventory-app
    ports:
      - ${INVENTORY_HOST_PORT}:${INVENTORY_PORT}
    depends_on:
      - inventory-database

  billing-app:
    build:
      context: ./srcs/billing-app
      dockerfile: Dockerfile
    networks:
      - app_network
    container_name: billing-app
    ports:
      - ${BILLING_HOST_PORT}:${BILLING_PORT}
    depends_on:
      - billing-database
      - rabbitmq


  api-gateway-app:
    build:
      context: ./srcs/api-gateway
      dockerfile: Dockerfile
    networks:
      - app_network
    container_name: api-gateway-app
    ports:
      - ${API_GATEWAY_PORT}:${API_GATEWAY_PORT}
    depends_on:
      - inventory-app
      - billing-app


volumes:
  inventory_postgres_data:
  billing_postgres_data:
  api-gateway-app:

