apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-app
  labels:
    app: api-gateway-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-app
  template:
    metadata:
      labels:
        app: api-gateway-app
    spec:
      containers:
      - name: api-gateway-app
        image: stepanti/orchestrator-api-gateway-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: RABBITMQ_HOST_ADDRESS
          valueFrom:
            configMapKeyRef:
                name: rabbitmq-configmap
                key: rabbitmq_url
        - name: RABBITMQ_QUEUE_NAME
          valueFrom: 
            configMapKeyRef:
                name: rabbitmq-configmap
                key: rabbitmq_queue_name
        - name: INVENTORY_HOST
          valueFrom: 
            configMapKeyRef:
              name: api-gateway-configmap
              key: inventory_app_url
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-app-service
spec:
  selector:
    app: api-gateway-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: api-gateway-app-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api-gateway-app
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
