apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing-database
  labels:
    app: billing-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: billing-database
  template:
    metadata:
      labels:
        app: billing-database
    spec:
      containers:
      - name: billing-database
        image: postgres:13.9-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: billing-db-secret
                key: billing-db-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: billing-db-secret
                key: billing-db-password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: billing-configmap
                key: billing_database_name
        volumeMounts:
          - name: init-scripts
            mountPath: /docker-entrypoint-initdb.d/init.sql
            subPath: init.sql
          - name: billing-db-volume
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-scripts
          configMap:
            name: billing-configmap
            items:
              - key: init.sql
                path: init.sql
        - name: billing-db-volume
          persistentVolumeClaim:
            claimName: billing-db-volume
---
apiVersion: v1
kind: Service
metadata:
  name: billing-database-service
spec:
  selector:
    app: billing-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: billing-db-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi