apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: inventory-database
  labels:
    app: inventory-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-database
  template:
    metadata:
      labels:
        app: inventory-database
    spec:
      containers:
      - name: inventory-database
        image: postgres:13.9-alpine
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: inventory-db-secret
                key: inventory-db-username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inventory-db-secret
                key: inventory-db-password
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: inventory-configmap
                key: inventory_database_name
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata 
        volumeMounts:
          - name: init-scripts
            mountPath: /docker-entrypoint-initdb.d/init.sql
            subPath: init.sql
          - name: inventory-db-volume
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: init-scripts
          configMap:
            name: inventory-configmap
            items:
              - key: init.sql
                path: init.sql
        - name: inventory-db-volume
          persistentVolumeClaim:
            claimName: inventory-db-volume
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-database-service
spec:
  selector:
    app: inventory-database
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-db-volume
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
