apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-app
  labels:
    app: inventory-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-app
  template:
    metadata:
      labels:
        app: inventory-app
    spec:
      containers:
      - name: inventory-app 
        image: stepanti/orchestrator-inventory-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: INVENTORY_DB_USER
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: inventory-db-username
        - name: INVENTORY_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inventory-db-secret
              key: inventory-db-password
        - name: INVENTORY_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: inventory-configmap
              key: inventory_database_name
        - name: INVENTORY_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: inventory-configmap
              key: inventory_database_url
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-app-service
spec:
  selector:
    app: inventory-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080