apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13.0-rc.2-alpine
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_QUEUE_NAME
          valueFrom:
            configMapKeyRef:
              name: rabbitmq-configmap
              key: rabbitmq_queue_name
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
      targetPort: 5672
