version: '3.8'

networks:
  rabbitmq_network:
    driver: bridge

  database_network:
    driver: bridge

services:
  database:
    image: postgres:13.9-alpine
    container_name: psql_container2
    networks:
      - database_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data  # Define the volume here

  pg-admin:
    image: dpage/pgadmin4:6.0
    container_name: pg-admin1
    networks:
      - database_network
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
  rabbitmq:
    image: rabbitmq:3.13-alpine
    container_name: rabbitmq_container
    networks:
      - rabbitmq_network
    ports:
      - "5672:5672"
    volumes:
      - ~/.docker-conf/rabbitmq/data:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log:/var/log/rabbitmq

volumes:
  postgres:
